const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE' ,


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS' ,
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL' ,
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //ADMIN
    FETCH_GENDER_START: 'FETCH_GENDER_START' ,
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS' ,
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL' ,

   
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS' ,
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL' , 

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS' ,
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL' , 


    // SAVE USER SUCCESS
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS' ,
    CREATE_USER_FAIL: 'CREATE_USER_FAIL' ,

    // FETCH ALL USER 
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILD: 'FETCH_ALL_USERS_FAILD' ,

    // DELETE USER
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS' ,
    DELETE_USER_FAIL: 'DELETE_USER_FAIL' ,

    // EDIT USER
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS' ,
    EDIT_USER_FAIL: 'EDIT_USER_FAIL' ,

    // FETCH TOP DOCTOR
    FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS' ,
    FETCH_TOP_DOCTORS_FAIL: 'FETCH_TOP_DOCTORS_FAIL' , 
    // FETCH ALL DOCTOR
    FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS' ,
    FETCH_ALL_DOCTORS_FAIL: 'FETCH_ALL_DOCTORS_FAIL' , 
    // SAVE DETAIL DOCTOR
    SAVE_DETAIL_DOCTORS_SUCCESS: 'SAVE_DETAIL_DOCTORS_SUCCESS' ,
    SAVE_DETAIL_DOCTORS_FAIl: 'SAVE_DETAIL_DOCTORS_FAIL', 
    
    // GET ALL CODE 
    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS: 'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS' ,
    FETCH_ALLCODE_SCHEDULE_TIME_FAIL: 'FETCH_ALLCODE_SCHEDULE_TIME_FAIL', 

     // LOADING
     LOADING_MODAL_SUCCESS: 'LOADING_MODAL_SUCCESS' ,
     LOADING_MODAL_FAIL: 'LOADING_MODAL_FAIL', 
    

    // FETCH DOCTOR PRICES
    FETCH_REQUIRED_DOCTOR_START: 'FETCH_REQUIRED_DOCTOR_START',
    FETCH_REQUIRED_DOCTOR_SUCCESS: 'FETCH_REQUIRED_DOCTOR_SUCCESS',
    FETCH_REQUIRED_DOCTOR_FAIL : 'FETCH_REQUIRED_DOCTOR_FAIL'

})

export default actionTypes;